---
name: Benchmarks

on:
  workflow_dispatch: {}  # Allow manual triggering
  push:
    branches: [develop, master]
  pull_request:
    branches: [develop, master]

jobs:
  benchmark:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET 8.0
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Disable broken NuGet source
        run: >
          dotnet nuget disable source gitversiontemp
          --configfile src/NuGet.Config

      - name: Restore dependencies
        run: >
          dotnet restore
          ./src/DotNet.Glob.Benchmarks/DotNet.Glob.Benchmarks.csproj

      - name: Build benchmarks
        run: >
          dotnet build
          ./src/DotNet.Glob.Benchmarks/DotNet.Glob.Benchmarks.csproj
          -c Release --no-restore -p:SignAssembly=false

      - name: Run BaselineRegexGlobCompileBenchmarks
        timeout-minutes: 5
        run: >
          dotnet run
          --project ./src/DotNet.Glob.Benchmarks/DotNet.Glob.Benchmarks.csproj
          -c Release --no-build -p:SignAssembly=false
          --framework net8.0
          -- --filter "*BaselineRegexGlobCompileBenchmarks*" --job dry

      - name: Run BaselineRegexIsMatchFalseBenchmarks
        timeout-minutes: 5
        run: >
          dotnet run
          --project ./src/DotNet.Glob.Benchmarks/DotNet.Glob.Benchmarks.csproj
          -c Release --no-build -p:SignAssembly=false
          --framework net8.0
          -- --filter "*BaselineRegexIsMatchFalseBenchmarks*" --job dry

      - name: Run BaselineRegexIsMatchTrueBenchmarks
        timeout-minutes: 5
        run: >
          dotnet run
          --project ./src/DotNet.Glob.Benchmarks/DotNet.Glob.Benchmarks.csproj
          -c Release --no-build -p:SignAssembly=false
          --framework net8.0
          -- --filter "*BaselineRegexIsMatchTrueBenchmarks*" --job dry

      - name: Run DotNetGlobBenchmarks
        timeout-minutes: 5
        run: >
          dotnet run
          --project ./src/DotNet.Glob.Benchmarks/DotNet.Glob.Benchmarks.csproj
          -c Release --no-build -p:SignAssembly=false
          --framework net8.0
          -- --filter "*DotNetGlobBenchmarks*" --job dry

      - name: Run RegexGlobIsMatchBenchmarks
        timeout-minutes: 5
        run: >
          dotnet run
          --project ./src/DotNet.Glob.Benchmarks/DotNet.Glob.Benchmarks.csproj
          -c Release --no-build -p:SignAssembly=false
          --framework net8.0
          -- --filter "*RegexGlobIsMatchBenchmarks*" --job dry

      - name: Upload benchmark results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: benchmark-results
          path: BenchmarkDotNet.Artifacts/**/*
